import type { CellMeta, CellType } from './types'

export const CELL_META: Record<CellType, CellMeta> = {
  ENT: {
    type: 'ENT',
    name: 'Entry corridor',
    description: 'Permitted synthetic entry point on the superior surface.',
    color: '#22d3ee',
    noGo: false,
    risk: 0.05,
    reward: 0,
  },
  WM_SAFE: {
    type: 'WM_SAFE',
    name: 'Safe white matter',
    description: 'Low-risk corridor tissue the probe may traverse.',
    color: '#64748b',
    noGo: false,
    risk: 0.1,
    reward: 0.05,
  },
  MOT_LEG: {
    type: 'MOT_LEG',
    name: 'Motor cortex — leg',
    description: 'Eloquent motor territory. Hard no-go in this simulation.',
    color: '#f59e0b',
    noGo: true,
    risk: 0.85,
    reward: -0.6,
  },
  MOT_TRUNK: {
    type: 'MOT_TRUNK',
    name: 'Motor cortex — trunk',
    description: 'Eloquent motor territory. Hard no-go in this simulation.',
    color: '#f59e0b',
    noGo: true,
    risk: 0.85,
    reward: -0.6,
  },
  MOT_ARM: {
    type: 'MOT_ARM',
    name: 'Motor cortex — arm',
    description: 'Eloquent motor territory. Hard no-go in this simulation.',
    color: '#fb923c',
    noGo: true,
    risk: 0.9,
    reward: -0.7,
  },
  MOT_HAND: {
    type: 'MOT_HAND',
    name: 'Motor cortex — hand',
    description:
      'Scenario-relevant hand motor representation. Highlighted context, and a hard no-go.',
    color: '#fbbf24',
    noGo: true,
    risk: 0.95,
    reward: -0.8,
  },
  MOT_FACE: {
    type: 'MOT_FACE',
    name: 'Motor cortex — face',
    description: 'Eloquent motor territory. Hard no-go in this simulation.',
    color: '#f59e0b',
    noGo: true,
    risk: 0.85,
    reward: -0.6,
  },
  SENS: {
    type: 'SENS',
    name: 'Sensory territory',
    description: 'Somatosensory tissue posterior to the target. Hard no-go.',
    color: '#38bdf8',
    noGo: true,
    risk: 0.8,
    reward: -0.5,
  },
  THAL: {
    type: 'THAL',
    name: 'Thalamic tissue',
    description: 'Generic deep thalamic tissue surrounding the target network.',
    color: '#a855f7',
    noGo: false,
    risk: 0.35,
    reward: 0.2,
  },
  VIM_NEAR: {
    type: 'VIM_NEAR',
    name: 'Near-target network',
    description: 'Conceptual border zone adjacent to the tremor network.',
    color: '#c084fc',
    noGo: false,
    risk: 0.3,
    reward: 0.45,
  },
  VIM_TARGET: {
    type: 'VIM_TARGET',
    name: 'Tremor-network target',
    description: 'Conceptual tremor-network goal cell for this scenario.',
    color: '#34ff9b',
    noGo: false,
    risk: 0.2,
    reward: 1,
  },
  IC_AVOID: {
    type: 'IC_AVOID',
    name: 'Internal-capsule analogue',
    description: 'Dense synthetic fibre bundle. Hard no-go.',
    color: '#ff4d6a',
    noGo: true,
    risk: 1,
    reward: -1,
  },
  VENT_AVOID: {
    type: 'VENT_AVOID',
    name: 'Ventricle analogue',
    description: 'Fluid-filled cavity analogue. Hard no-go.',
    color: '#f43f5e',
    noGo: true,
    risk: 1,
    reward: -1,
  },
  BRAINSTEM_AVOID: {
    type: 'BRAINSTEM_AVOID',
    name: 'Brainstem analogue',
    description: 'Critical inferior structure analogue. Hard no-go.',
    color: '#e11d48',
    noGo: true,
    risk: 1,
    reward: -1,
  },
  CEREB_NET: {
    type: 'CEREB_NET',
    name: 'Cerebellar network',
    description:
      'Conceptual cerebellar relay network, modelled but never traversed.',
    color: '#fb7185',
    noGo: true,
    risk: 0.9,
    reward: -0.8,
  },
  OUTSIDE: {
    type: 'OUTSIDE',
    name: 'Outside modelled volume',
    description:
      'Beyond the simulated left-hemisphere cutaway. Hard no-go and not rendered.',
    color: '#1e293b',
    noGo: true,
    risk: 1,
    reward: -1,
  },
}

export const LEGEND_ORDER: CellType[] = [
  'ENT',
  'WM_SAFE',
  'THAL',
  'VIM_NEAR',
  'VIM_TARGET',
  'MOT_HAND',
  'MOT_ARM',
  'MOT_LEG',
  'MOT_TRUNK',
  'MOT_FACE',
  'SENS',
  'IC_AVOID',
  'VENT_AVOID',
  'BRAINSTEM_AVOID',
  'CEREB_NET',
  'OUTSIDE',
]

export const isNoGo = (type: CellType): boolean => CELL_META[type].noGo
