import { Boxes, Brain, Play, Route, ShieldAlert } from 'lucide-react'
import { useSimulation } from '../../state/simulationStore'

const points = [
  {
    icon: Boxes,
    title: 'A tiny invented world',
    body: 'The brain here is invented, not a scan — either a stylised world generated by Reactor that you walk through, or the voxel grid itself. Underneath both sits a 4×4×4 grid of labelled cells: entry corridors, safe white matter, thalamic tissue, and no-go zones.',
  },
  {
    icon: Brain,
    title: 'A world model that predicts',
    body: 'Before every move the simulation states where the probe would land, what tissue it expects there, and the risk and reward it assigns — all deterministic.',
  },
  {
    icon: Route,
    title: 'A planner that respects hard limits',
    body: 'An A* search finds the cheapest safe route from an entry voxel to the conceptual target. No-go tissue is filtered out entirely, so it can never be traded away for a shorter path.',
  },
]

export const IntroOverlay = () => {
  const start = useSimulation((state) => state.start)
  const scenario = useSimulation((state) => state.scenario)

  return (
    <div className="absolute inset-0 z-30 flex items-center justify-center bg-[rgba(3,5,12,0.86)] p-6 backdrop-blur-md">
      <div className="glass max-h-full w-full max-w-3xl overflow-y-auto rounded-3xl p-8">
        <div className="flex items-center gap-3">
          <span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-400/15 text-sky-300">
            <Brain className="h-5 w-5" aria-hidden />
          </span>
          <div>
            <h1 className="text-2xl font-semibold tracking-tight text-slate-50">
              NeuroGrid
            </h1>
            <p className="text-[13px] text-slate-400">
              Synthetic world-model simulation of a robotic electrode
            </p>
          </div>
        </div>

        <div className="mt-5 flex items-start gap-3 rounded-xl border border-amber-400/30 bg-amber-400/10 px-4 py-3 text-amber-100">
          <ShieldAlert className="mt-[2px] h-4 w-4 shrink-0 text-amber-300" aria-hidden />
          <p className="text-[12.5px] leading-relaxed">
            This is an educational proof of concept. Everything on screen is
            invented: the anatomy, the coordinates, and the risk numbers. It is
            not medical software and must never be used for diagnosis, surgical
            planning, or patient-specific decisions.
          </p>
        </div>

        <div className="mt-6 grid gap-4 sm:grid-cols-3">
          {points.map(({ icon: Icon, title, body }) => (
            <div
              key={title}
              className="rounded-2xl border border-slate-700/50 bg-slate-900/40 p-4"
            >
              <Icon className="h-4 w-4 text-sky-400" aria-hidden />
              <h2 className="mt-2 text-[13px] font-semibold text-slate-100">
                {title}
              </h2>
              <p className="mt-1 text-[12px] leading-relaxed text-slate-400">
                {body}
              </p>
            </div>
          ))}
        </div>

        <div className="mt-6 rounded-2xl border border-slate-700/50 bg-slate-900/40 p-4">
          <p className="text-[11px] font-semibold tracking-[0.18em] text-slate-500 uppercase">
            Loaded scenario
          </p>
          <p className="mt-1 text-[13px] text-slate-200">{scenario.title}</p>
          <p className="mt-1 text-[12px] leading-relaxed text-slate-400">
            {scenario.summary}
          </p>
        </div>

        <button
          type="button"
          onClick={start}
          className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-sky-500/90 px-4 py-3 text-[13px] font-semibold text-slate-950 transition hover:bg-sky-400"
        >
          <Play className="h-4 w-4" aria-hidden />
          Enter the simulation
        </button>
      </div>
    </div>
  )
}
